// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbK-GoIyA9dlXJbSFbBxcmod5NK6DncTo',
    appId: '1:640196927691:android:30f59da6b1505482ea7b4e',
    messagingSenderId: '640196927691',
    projectId: 'roomrentinggroup1',
    storageBucket: 'roomrentinggroup1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRxH1msTztRuKBVW3pswHioibZtRHXPqA',
    appId: '1:640196927691:ios:3a70ffd1e913a2fbea7b4e',
    messagingSenderId: '640196927691',
    projectId: 'roomrentinggroup1',
    storageBucket: 'roomrentinggroup1.firebasestorage.app',
    iosBundleId: 'com.example.roomRentingGroup1',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdIW8_4FyQFCSTsGY-nL98PmVac1K5R1g',
    appId: '1:640196927691:web:aec5b031f10ff6c9ea7b4e',
    messagingSenderId: '640196927691',
    projectId: 'roomrentinggroup1',
    authDomain: 'roomrentinggroup1.firebaseapp.com',
    storageBucket: 'roomrentinggroup1.firebasestorage.app',
  );

}